import { FREE_SPACE } from "./constants";

// https://www.instagram.com/p/CMm2gFEFvo_/
export const initialOptions = [
  [
    'JONATHAN SAYS "EXACTLY RIGHT"',
    '"WE\'RE HIRING!"',
    "COACHES DISCUSS THE 3 OF THEM DOING A TRIATHLON IN THE FUTURE",
    `NATE'S FAMOUS "LONG BOMB" ATTACK IS BROUGHT UP`,
    'THE TERM "BRO SCIENCE" IS USED',
  ],
  [
    "KEEGAN SWENSON IS MENTIONED",
    'THE TERM "COGNITIVE LOAD" IS USED',
    "NOT ALL TSS IS CREATED EQUAL",
    "A QUESTION ABOUT STRENGTH TRAINING IS DISCUSSED",
    "YOU STILL DON'T UNDERSTAND SOMETHING THAT WAS THOROUGHLY EXPLAINED",
  ],
  [
    "JONATHAN DROPS THAT TR SPONSORS THE STAN'S PIVOT TEAM",
    "CHAD DOES A DEEP DIVE LASTING LONGER THAN 5 MINUTES",
    FREE_SPACE,
    '"CONSULT YOUR DOCTOR"',
    "COACHES DEFER TO EX PRO AMBER PIERCE'S EXPERIENCE",
  ],
  [
    '"I DON\'T HAVE ANY DATA TO BACK THIS UP"',
    "LEADVILLE OR CAPE EPIC ARE MENTIONED",
    "LOCAL SPRINTER JOSE IS REFERENCED",
    "5 STAR RATING PLZ",
    "LANCE'S PODCAST IS ALLUDED TO",
  ],
  [
    "NATE'S HEIGHT IS ALLUDED TO",
    "PETE MORRIS SOUNDS CHILL AF WHILE DISCUSSING INTENSE RACING",
    "SPRINTING FORM IS DISCUSSED",
    "JONATHAN'S WEAK STOMACH IS TALKED ABOUT",
    "ANYONE'S FTP IS MENTIONED",
  ],
];

export const initialSelections = [
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
];
